# https://travis-ci.org/dr-prodigy/hompi

language: python

python:
    - "3.10"
    - "3.11"
    - "3.12"
    - "3.13"

install:
    - pip install -U pip setuptools wheel
    - pip install -e ".[dev]"

script:
    - flake8 src
    - python -c "import hompi; from hompi.app import main; from hompi.ws_api import main as api_main; print(hompi.__version__)"
