# https://travis-ci.org/dr-prodigy/hompi

language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - pypy
    - pypy3

env:

install:
    - ./scripts/install.py
    - pip install flake8

before_script:

script:
    - flake8 *.py

after_success:
