#!/bin/bash

# Copyright (C)2018-24 Maurizio Montel (dr-prodigy) <maurizio.montel@gmail.com>
# This file is part of hompi <https://github.com/dr-prodigy/hompi>.
#
# hompi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# hompi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with hompi.  If not, see <http://www.gnu.org/licenses/>.

# Dev shortcut: run the main process from the project root so config.py
# remains importable. Prefers the editable-install console script.

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
export PYTHONIOENCODING=utf-8
# Project root must stay on PYTHONPATH for ``import config``
export PYTHONPATH="${ROOT}${PYTHONPATH:+:$PYTHONPATH}"

if [[ -x "${ROOT}/venv/bin/hompi" ]]; then
  exec "${ROOT}/venv/bin/hompi" "$@"
fi

# Fallback before ``pip install -e .``
export PYTHONPATH="${ROOT}/src:${PYTHONPATH}"
exec "${ROOT}/bin/hompi" "$@"
